#!/usr/bin/env bash
# Context Checkpoint Hook (PreCompact)
# Auto-creates progress summaries before context compaction
# Inspired by eigent's context pruning patterns for research agents

set -euo pipefail

# Parse hook data (PreCompact doesn't have much data, but we can still log)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATE_ONLY=$(date -u +"%Y-%m-%d")

# Create .agent-notes directory if it doesn't exist
NOTES_DIR="${PWD}/.agent-notes"
mkdir -p "$NOTES_DIR"

# Checkpoint log file
CHECKPOINT_FILE="${NOTES_DIR}/checkpoints-${DATE_ONLY}.md"

# Initialize checkpoint file if it doesn't exist
if [ ! -f "$CHECKPOINT_FILE" ]; then
  cat > "$CHECKPOINT_FILE" << EOF
# Context Checkpoints - ${DATE_ONLY}

Auto-generated by workforce-assistant plugin.
Marks when context compaction occurred during long sessions.

**Purpose:** Track session boundaries for later review.

---

EOF
fi

# Create checkpoint marker
cat >> "$CHECKPOINT_FILE" << EOF

## Checkpoint: ${TIMESTAMP}

Context compaction triggered. If this session involves:
- Multi-step research: Review .agent-notes/research-${DATE_ONLY}.md
- Implementation work: Review .agent-notes/tool-usage-log.md

**Next actions:**
- Continue with focused context
- Reference notes for cross-session continuity

---

EOF

# Suggest to Claude to create a summary
cat << EOF
{
  "status": "checkpoint_created",
  "file": "${CHECKPOINT_FILE}",
  "message": "Context compaction detected. Consider summarizing progress in .agent-notes/ before context is pruned.",
  "suggestion": "Review: (1) What has been accomplished? (2) What remains? (3) Any blockers?"
}
EOF

exit 0
