#!/usr/bin/env bash
# Tool Lifecycle Logger Hook (PostToolUse)
# Automatically logs tool usage patterns to build usage playbooks
# Inspired by eigent's @listen_toolkit() pattern

set -euo pipefail

# Parse hook data from stdin
HOOK_DATA=$(cat)

# Extract tool information
TOOL_NAME=$(echo "$HOOK_DATA" | jq -r '.tool // "unknown"')
TOOL_RESULT=$(echo "$HOOK_DATA" | jq -r '.result // "" | tostring' | head -c 500)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create .agent-notes directory if it doesn't exist
NOTES_DIR="${PWD}/.agent-notes"
mkdir -p "$NOTES_DIR"

# Log file location
LOG_FILE="${NOTES_DIR}/tool-usage-log.md"

# Initialize log file if it doesn't exist
if [ ! -f "$LOG_FILE" ]; then
  cat > "$LOG_FILE" << 'EOF'
# Tool Usage Log

Auto-generated by workforce-assistant plugin.
Tracks tool usage patterns to build effective playbooks.

---

EOF
fi

# Append tool usage entry
cat >> "$LOG_FILE" << EOF

## ${TIMESTAMP} - ${TOOL_NAME}

**Result Preview:**
\`\`\`
${TOOL_RESULT}
\`\`\`

EOF

# Output success message (silent - no user notification needed)
echo "{\"status\": \"logged\", \"tool\": \"${TOOL_NAME}\"}"
